### ISSUE TITLE
关于次数怪的血量加成

### ISSUE THREAD

**Issue by Eletary** [tanch-p/tomimi-chan#13]
亡者行军的深池小怪，显然击倒需要次数大于5。

随机找了一个证据：https://www.bilibili.com/video/av316695101

01:30 处，上面最右侧的小怪，在第二阶段受到至少玛恩纳斩2刀4次伤害和苇草1次平a后未死亡

**Comment by tanch-p** [comment]
请问你看的数据是什么难度的？

**Comment by Eletary** [comment]
> 请问你看的数据是什么难度的？

对不起，应该是换设备难度重置了。其实看的n0.
