### ISSUE TITLE
关卡 没有尽头的路 高普尼克数据问题

### ISSUE THREAD

**Issue by QINGMINGMIKU** [tanch-p/tomimi-chan#5]
二层其他关卡高普尼克血量均为4w8左右，攻击力3k。然而没有尽头的路是11w血量，5k攻击。请问这个数据是否为正常数据？

**Comment by QINGMINGMIKU** [comment]
查询鸭爵与流泪小子数据后发现有同样问题

**Comment by tanch-p** [comment]
没有尽头的路的隐藏敌人的面板是用level1，其他二层都用level0。如果数据有疑问时可以参考prts.wiki，那边大大概率是对的
