### ISSUE TITLE
违和关卡界面文本错误

### ISSUE THREAD

**Issue by QINGMINGMIKU** [tanch-p/tomimi-chan#7]
![Screenshot_2023-10-18-02-42-41-99_df198e732186825c8df26e3c5a10d7cd](https://github.com/tanch-p/tomimi-chan/assets/100114861/3b7fa3ae-b51c-4c34-879e-13d140c0c02a)
错别字问题。
波次文本写为破次。

**Comment by tanch-p** [comment]
谢谢指点，已修改了
