### ISSUE TITLE
散华骑士团系列敌人技能伤害计算错误

### ISSUE THREAD

**Issue by Creeperac** [tanch-p/tomimi-chan#8]
<img width="972" alt="42bc327aa91d3d6c4e746ed43774347c" src="https://github.com/tanch-p/tomimi-chan/assets/110230535/1d27ff0d-dfce-4344-a3fd-baaf112ec063">
如图，250%计算为了300%。这使得和实际数据不符。

![image](https://github.com/tanch-p/tomimi-chan/assets/110230535/6a8213d4-f2a1-40fe-b98a-66247a9894c2)

狂信如火的数据中也有这个问题。

**Comment by tanch-p** [comment]
谢谢反馈，已把错误的数据修改了
