### ISSUE TITLE
恃强凌弱数值错误

### ISSUE THREAD

**Issue by QINGMINGMIKU** [tanch-p/tomimi-chan#9]
恃强凌弱关卡辐能源石虫数值为176，但实战表现中，该虫没有受到肉鸽加成。经测试，辐能源石虫在n15难度中攻击力仍为90，对精二焰影苇草造成了288点的高额法术伤害（无灼痕）。

**Comment by tanch-p** [comment]
竟然有这种事，等我有空再打不同难度看看是不是全难度都没加成

**Comment by tanch-p** [comment]
已确认辐能源石虫数值不会受到难易度属性加成
